company_name_search_database_dir: data/security_name_dbs
database:
  connection_string: postgres://aarongilman1:FxoSvg0chBQQtDh7OBm73IphJpCQ6MR2@securitiesdb.cic61ctm5cbx.us-east-1.rds.amazonaws.com:5432/securitiesdb2?sslmode=require&sslrootcert=config/rds-combined-ca-bundle.pem

log_level: info
database_log_level: error
quandl:
  api_key:  ZXWrUMgVHYz4kgK9FARR
  api_version: "2015-04-09"
